# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 73a715ef6de057453b901fe30497c6ac06ed93460fefae65d30f2a1e7dcb005cddcae925845049c2740a6540a683970fa2e3363f91e48ed1378e14a8f708386e

test:
  secret_key_base: 80edefdb69c8fc97b08c3332548a44be202670dde4822d9409ce633050d8b5d60684cd4498837150272cede66aff5e2f8dc0f42cd97e8ac075a8b7b64f37797c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
